stands_lst = {
    #-------------------------Стенды 3 части ниже-------------------------#
    "1": "Hamon",
    "2": "Star Platinum",
    "3": "Magician's Red",
    "4": "Hermit Purple",
    "5": "Silver Chariot",
    "6": "Hierophant Green",
    "7": "The Fool",
    "8": "The World",
    "9": "Tower of Gray",
    "10": "Dark Blue Moon",
    "11": "Strength",
    "12": "Ebony Devil",
    "13": "Yellow Temperance",
    "14": "Hanged Man",
    "15": "Emperor",
    "16": "Empress",
    "17": "Wheel of Fortune",
    "18": "Justice",
    "19": "Lovers",
    "20": "Sun",
    "21": "Death Thirteen",
    "22": "Judgement",
    "23": "High Priestess",
    "24": "Geb",
    "25": "Khnum",
    "26": "Tohth",
    "27": "Anubis",
    "28": "Bastet",
    "29": "Sethan",
    "30": "Osiris",
    "31": "Horus",
    "32": "Atum",
    "33": "Tenore Sax",
    "34": "Cream",
    #-------------------------Стенды 4 части ниже-------------------------#
    "35": "The Hand",
    "36": "Echoes ACT 1",
    "37": "Crazy Diamond",
    "38": "Bad Company",
    "39": "Heaven's Door",
    "40": "Killer Queen",
    "41": "Red Hot Chili Pepper",
    "42": "The Lock",
    "43": "Surface",
    "44": "Love Deluxe",
    "45": "Pearl Jam",
    "46": "Ratt",
    "47": "Harvest",
    "48": "Cinderella",
    "49": "Boy II Man",
    "50": "Earth Wind and Fire",
    "51": "Highway Star",
    "52": "Enigma",
    "53": "Cheap Trick",
    #-------------------------Стенды 5 части ниже-------------------------#
    "54": "Gold Experience",
    "55": "Sticky Fingers",
    "56": "Moody Blues",
    "57": "Sex Pistols",
    "58": "Aerosmith",
    "59": "Purple Haze",
    "60": "Spice Girl",
    "61": "King Crimson",
    "62": "Black Sabbath",
    "63": "Soft Machine",
    "64": "Kraft Work",
    "65": "Little Feet",
    "66": "Man in the Mirror",
    "67": "Mr.President",
    "68": "Beach Boy",
    "69": "The Grateful Dead",
    "70": "Baby Face",
    "71": "White Album",
    "72": "Clash",
    "73": "Talking Head",
    "74": "Notorious B.I.G",
    "75": "Metallica",
    "76": "Green Day",
    "77": "Oasis",
    "78": "Rolling Stones",
    #-------------------------Стенды 6 части ниже-------------------------#
    "79": "Stone Free",
    "80": "Kiss",
    "81": "Burning Down the House",
    "82": "Foo Fighters",
    "83": "Weather Report",
    "84": "Diver Down",
    "85": "Whitesnake",
    "86": "Goo Goo Dolls",
    "87": "Manhattan Transfer",
    "88": "Highway to Hell",
    "89": "Marilyn Manson",
    "90": "Jumpin' Jack Flash",
    "91": "Limp Bizkit",
    "92": "Survivor",
    "93": "Planet Waves",
    "94": "Dragon's Dream",
    "95": "Yo-Yo Ma",
    "96": "Green, Green Grass of Home",
    "97": "Jail House Lock",
    "98": "Bohemian Rhapsody",
    "99": "Sky High",
    "100": "Under World",
    #-------------------------Стенды 7 части ниже-------------------------#
    "101": "Tusk ACT 1",
    "102": "Ball Breaker",
    "103": "Oh! Lonesome Me",
    "104": "Scary Monsters",
    "105": "Cream Starter",
    "106": "Ticket to Ride",
    "107": "Dirty Deeds Done Dirt Cheap",
    "108": "In a Silent Way",
    "109": "Boku no Rhythm wo Kiitekure",
    "110": "Wired",
    "111": "Mandom",
    "112": "Catch the Rainbow",
    "113": "Tatoo You!",
    "114": "Tubular Bells",
    "115": "Civil War",
    "116": "The World: High Voltage",
    "117": "",
    "118": "",
    "119": "Holly's Stand",
    "120": "Joestar's Stand",
    "121": "Super Fly",
    "122": "Gold Experience: Over Heaven Requiem",
    "123": "Made in Heaven",
    "124": "The World: Over Heaven"
}

# Запись: Bohemian Rhapsody фото пропустил, Highway to Hell фото пропустил

# Стенды которые можно выиграть в розыгрышах / выбить при удачной победе с шансом (0.5) [Может быть шанс будет меньше]

upgrade_stands_lst = {
    "1": "Echoes ACT 2",
    "2": "Echoes ACT 3",
    "3": "Star Platinum: The World",
    "4": "Hermit Purple",
    "5": "Killer Queen: Bites The Dust",
    "6": "Killer Queen: Stray Cat",
    "7": "Killer Queen: Sheer Heart Attack",
    "8": "Gold Experience: Requiem",
    "9": "Silver Chariot Requiem",
    "10": "Star Platinum: Stone Ocean",
    "11": "C-Moon",
    "12": "Tusk ACT 2",
    "13": "Tusk ACT 3",
    "14": "Tusk ACT 4",
    "15": "D4C: Love Train",
}

# Стенды которые можно будет получить после того как их прокачаешь

items = {
    "1": "Stand Arrow",
    "2": "Requiem Arrow",
    "3": "Dio's Bone",
    "4": "The Key",
}
# итемы для прокачки

variations = {
    "1": "Вы решили слетать в другую страну чтобы поведать близких, они дали вам {}$ денег.",
    "2": "Находясь в квартире, вы решаете изучить высшую математику без причины, к уму прибавляется {}iq.",
    "3": "Вы решили изучить свой стенд более детально, каким-то магическим способом у вас в кошельке появилось {}$ денег.",
    "4": "Гуляя по городу и зайдя в тёмный район, вы заметили что кто-то идёт за вами, использовав навыки стенда вы скрылись и сохранили себе {}$ денег.",
    "5": "Зайдя в магазин вы решили купить пачку чипсов, вы заметили что вам дали лишнию сдачу в виде {}$!",
    "6": "Гуляя на улице, вы заметили на земле кошелёк. В нём было {}$!",
    "7": "Вы просто шли по дороге, но заметили как грабитель украл кошелёк у девушки. Вам удалось догнать его и вернуть кошелёк. Она дала вам вознаграждение в размере {}$!",
    "8": "Вы продали ненужный хлам в своей квартире, и получили за это {}$ денег.",
    "9": "Идя к другу через гетто, вы замечаете что за вами идёт шайка бандитов. Используя свой стенд, вы разбираетесь с ними. За это они дали вам {}$ денег, взамен на то чтобы вы их больше не трогали.",
    "10": "Вы находите дорогой телефон на земле, и решаете его продать. За его продажу вы получили {}$ денег.",
}
# вариации текстов для adventure

explore_levels = {
    1.00: "Спокойный городок",
    1.05: "Тёмный район",
    1.10: "Гетто",
    1.15: "Район мафии",
    1.20: "Чумной город",
    1.25: "Подвал в старинном доме",
    1.30: "Канализация чумного города",
    1.35: "Пустое село",
    1.40: "Особняк мафии",
    1.45: "Крыша особняка",
    1.50: "Ночной город",
    1.55: "Главная площадь ночного города",
    1.60: "Часовня",
    1.65: "Верхушка часовни",
    1.70: "Рай"
}
# уровни для эксплоура