stands_lst = {
    "1": "Hamon",
    "2": "Star Platinum",
    "3": "Magician's Red",
    "4": "Hermit Purple",
    "5": "Silver Chariot",
    "6": "Hierophant Green",
    "7": "The Fool",
    "8": "The World",
    "9": "Tower of Gray",
    "10": "Dark Blue Moon",
    "11": "Strength",
    "12": "Ebony Devil",
    "13": "Yellow Temperance",
    "14": "Hanged Man",
    "15": "Emperor",
    "16": "Empress",
    "17": "Wheel of Fortune",
    "18": "Justice",
    "19": "Lovers",
    "20": "Sun",
    "21": "Death Thirteen",
    "22": "Judgement",
    "23": "High Priestess",
    "24": "Geb",
    "25": "Khnum",
    "26": "Tohth",
    "27": "Anubis",
    "28": "Bastet",
    "29": "Sethan",
    "30": "Osiris",
    "31": "Horus",
    "32": "Atum",
    "33": "Tenore Sax",
    "34": "Cream",
    "35": "The Hand",
    "36": "Echoes ACT 1",
    "37": "Crazy Diamond",
    "38": "Bad Company",
    "39": "Heaven's Door",
    "40": "Killer Queen",
    "41": "Red Hot Chili Pepper",
    "42": "The Lock",
    "43": "Surface",
    "44": "Love Deluxe",
    "45": "Pearl Jam",
    "46": "Ratt",
    "47": "Harvest",
    "48": "Cinderella",
    "49": "Boy II Man",
    "50": "Earth Wind and Fire",
    "51": "Highway Star",
    "52": "Enigma",
    "53": "Cheap Trick",
    "54": "Gold Experience",
    "55": "Sticky Fingers",
    "56": "Moody Blues",
    "57": "Sex Pistols",
    "58": "Aerosmith",
    "59": "Purple Haze",
    "60": "Spice Girl",
    "61": "King Crimson",
    "62": "Black Sabbath",
    "63": "Soft Machine",
    "64": "Kraft Work",
    "65": "Little Feet",
    "66": "Man in the Mirror",
    "67": "Mr.President",
    "68": "Beach Boy",
    "69": "The Grateful Dead",
    "70": "Baby Face",
    "71": "White Album",
    "72": "Clash",
    "73": "Talking Head",
    "74": "Notorious B.I.G",
    "75": "Metallica",
    "76": "Green Day",
    "77": "Oasis",
    "78": "Rolling Stones",
    "79": "Stone Free",
    "80": "Kiss",
    "81": "Burning Down the House",
    "82": "Foo Fighters",
    "83": "Weather Report",
    "84": "Diver Down",
    "85": "Whitesnake",
    "86": "Goo Goo Dolls",
    "87": "Manhattan Transfer",
    "88": "Highway to Hell",
    "89": "Marilyn Manson",
    "90": "Jumpin' Jack Flash",
    "91": "Limp Bizkit",
    "92": "Survivor",
    "93": "Planet Waves",
    "94": "Dragon's Dream",
    "95": "Yo-Yo Ma",
    "96": "Green, Green Grass of Home",
    "97": "Jail House Lock",
    "98": "Bohemian Rhapsody",
    "99": "Sky High",
    "100": "Under World",
    "101": "Tusk 1",
    "102": "Ball Breaker",
    "103": "Achtung Baby",
    "104": "Holly's Stand",
    "105": "Joestar's Stand",
    "106": "Atom Heart Father",
    "107": "Super Fly",
    "108": "Gold Experience: Over Heaven Requiem",
    "109": "Made in Heaven",
    "110": "The World: Over Heaven"
}

# Нумерация стендов

# Стенды которые можно выиграть в розыгрышах / выбить при удачной победе с шансом (0.5) [Может быть шанс будет меньше]

upgrade_stands_lst = {
    "1": "Echoes ACT 2",
    "2": "Echoes ACT 3",
    "3": "Star Platinum: The World",
    "4": "Hermit Purple",
    "5": "Killer Queen: Bites The Dust",
    "6": "Killer Queen: Stray Cat",
    "7": "Killer Queen: Sheer Heart Attack",
    "8": "Gold Experience: Requiem",
    "9": "Silver Chariot Requiem",
    "10": "Star Platinum: Stone Ocean",
    "11": "C-Moon",
    "12": "Tusk 2",
    "13": "Tusk 3",
    "14": "Tusk 4",
}

# Стенды которые можно будет получить после того как их прокачаешь

items = {
    "1": "Stand Arrow",
    "2": "Requiem Arrow",
    "3": "Dio's Bone",
    "4": "The Key",
}
# итемы для прокачки

variations = {
    "1": "Вы решили слетать в другую страну чтобы поведать близких, за это вы получили {}$ денег.",
    "2": "Находясь в квартире, вы решаете изучить высшую математику без причины, к уму прибавляется {}iq.",
    "3": "Вы решили изучить свой стенд более детально, каким-то магическим способом у вас в кошельке появилось {}$ денег.",
    "4": "Гуляя по городу и зайдя в тёмный район, вы заметили что кто-то идёт за вами, использовав навыки стенда вы скрылись и сохранили себе {}$ денег."
}
# вариации текстов для adventure